### ISSUE TITLE
Real variables ignored

### ISSUE THREAD

**Issue by Cyber-EX** [natenorrish/enhanced-basic-transpiler#1]
It handles integer and string variables, but it ignores real variables (the ones without % or $).

This code:
```
VAR1% = 10
VAR2$ = "20"
VAR3 = 30
```

Becomes:
```
10 AA% = 10
20 AB$ = "20"
30 VAR3 = 30
```

**Comment by natenorrish** [comment]
The reason for this is because I need to get a list of all the standard commands (PRINT, CLS, etc.), to determine if it's a variable or without the type character.

I'll see what I can do :)

**Comment by Cyber-EX** [comment]
Yeah, I see. Well, as a fast solution you coluld use some other symbol for indicating real variable.
For example this code:
```
VAR1% = 10
VAR2$ = "20"
VAR3# = 30
```
Could become:
```
10 AA% = 10
20 AB$ = "20"
30 AC = 30
```

**Comment by natenorrish** [comment]
Sorry, forgot to mention, you can use ! 

VAR3! = 30

I'll add in # actually, I think that makes more sense as it can be "number" as well.

**Comment by natenorrish** [comment]
OK, I've just pushed a new version to use # - I'll close this out once actually fixed.

**Comment by Cyber-EX** [comment]
Cool. Though I did not understand why # is better. What can be a "number"?

**Comment by natenorrish** [comment]
The # also means "number", seeing as you can only assign a string to a variable with $, it would make sense to use this symbol for variables without a type suffix, as the values will always be a number.

**Comment by greg-king5** [comment]
X16 BASIC has `GET#`, `INPUT#`, and `PRINT#` keywords.

**Comment by Cyber-EX** [comment]
I think it's fine to use !

**Comment by Cyber-EX** [comment]
I opened this issue, because I did not know about !
So if # may apeear in keywords, I think it's safer to use ! for real numbers

**Comment by natenorrish** [comment]
In Qbasic # is actually a type character, so it's technically valid syntax. I will add in GET, INPUT, and PRINT as exceptions for variable names.

QBasic has five built-in types: INTEGER (%), LONG(&) integer, SINGLE(!) float, DOUBLE(#) float and STRING($)

**Comment by natenorrish** [comment]
@Cyber-EX @greg-king5  - I've updated the command line arguments, so just run the script without any options and it'll display the help.

**Comment by natenorrish** [comment]
@Cyber-EX @greg-king5 - this is no longer an issue as I have completely recoded the script to parse BASIC and output a tokenized PRG file. I've also renamed the main script and changed the options, so please take a look at the README file.
