### ISSUE TITLE
PRINT CHR$($0F)

### ISSUE THREAD

**Issue by Cyber-EX** [natenorrish/enhanced-basic-transpiler#2]
Why do you add PRINT CHR$($0F) at the begining of output file?
I see it switches X16 to lowercase mode.

**Comment by natenorrish** [comment]
I wanted to be able to use lowercase characters, which doesn't appear to be possible. I can remove that or add it in as an option perhaps?

**Comment by natenorrish** [comment]
Without it:

![image](https://user-images.githubusercontent.com/42674085/95322777-c2e2a400-08e8-11eb-8037-b0dc605339b4.png)

Produces this:
![image](https://user-images.githubusercontent.com/42674085/95322754-b5c5b500-08e8-11eb-9c8c-51a5f0ab7d39.png)

**Comment by Cyber-EX** [comment]
Yeah, makes sense. That's just the nature of PETSCII character set.
No, don't remove that. Adding an option would be nice.

**Comment by greg-king5** [comment]
You can shorten that line to:
```
\X0F
```

**Comment by natenorrish** [comment]
Updated to \x0F and added in -p to use PETSCII character set.

Thanks guys
